# Generated by Django 6.0.7 on 2026-07-30 21:19

import django.db.models.deletion
import django.utils.timezone
import encrypted_model_fields.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome/Identificador do perfil')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail (conta Facebook)')),
                ('senha', encrypted_model_fields.fields.EncryptedCharField(help_text='Armazenada criptografada (FIELD_ENCRYPTION_KEY). Nunca exibida em texto puro.', verbose_name='Senha')),
                ('tipo_autenticacao', models.CharField(choices=[('nenhuma', 'Nenhuma'), ('sms', '2FA via SMS'), ('app_autenticador', '2FA via app autenticador'), ('email_recuperacao', 'E-mail de recuperação')], default='nenhuma', max_length=20, verbose_name='Tipo de autenticação')),
                ('dados_autenticacao', encrypted_model_fields.fields.EncryptedTextField(blank=True, default='', help_text='Códigos de backup/recuperação, segredo do app autenticador etc. Criptografado.', verbose_name='Dados de autenticação adicionais')),
                ('adspower_id', models.CharField(blank=True, help_text='ID do perfil no AdsPower (ex: kp0a1b2c3d4).', max_length=150, verbose_name='Perfil/Proxy no AdsPower')),
                ('fase_atual', models.CharField(choices=[('perfil_criado', '1. Perfil criado no AdsPower'), ('login_facebook', '2. Login/acesso ao perfil no Facebook'), ('verificacao_pagina', '3. Verificação de página do Facebook'), ('criacao_pagina', '4. Criação da página'), ('vinculo_whatsapp', '5. Vínculo da conta do WhatsApp'), ('geracao_bm', '6. Geração do Business Manager'), ('concluido', '7. Concluído / Ativo')], default='perfil_criado', max_length=30, verbose_name='Fase atual')),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('banido', 'Banido'), ('suspenso', 'Suspenso'), ('pausado', 'Pausado')], default='ativo', max_length=20, verbose_name='Status')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Última atualização')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações/Notas')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perfis_responsavel', to=settings.AUTH_USER_MODEL, verbose_name='Responsável')),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfis',
                'ordering': ['-atualizado_em'],
            },
        ),
        migrations.CreateModel(
            name='PhaseHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fase', models.CharField(choices=[('perfil_criado', '1. Perfil criado no AdsPower'), ('login_facebook', '2. Login/acesso ao perfil no Facebook'), ('verificacao_pagina', '3. Verificação de página do Facebook'), ('criacao_pagina', '4. Criação da página'), ('vinculo_whatsapp', '5. Vínculo da conta do WhatsApp'), ('geracao_bm', '6. Geração do Business Manager'), ('concluido', '7. Concluído / Ativo')], max_length=30, verbose_name='Fase')),
                ('data_hora', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data/hora da mudança')),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_fases', to='profiles.profile', verbose_name='Perfil')),
            ],
            options={
                'verbose_name': 'Histórico de fase',
                'verbose_name_plural': 'Histórico de fases',
                'ordering': ['-data_hora'],
            },
        ),
        migrations.CreateModel(
            name='PageInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_pagina', models.CharField(max_length=200, verbose_name='Nome da página')),
                ('link_pagina', models.URLField(blank=True, verbose_name='Link da página')),
                ('data_criacao', models.DateField(blank=True, null=True, verbose_name='Data de criação da página')),
                ('status', models.CharField(choices=[('criada', 'Criada'), ('pendente', 'Pendente'), ('falhou', 'Falhou')], default='pendente', max_length=20, verbose_name='Status')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paginas', to='profiles.profile', verbose_name='Perfil')),
            ],
            options={
                'verbose_name': 'Página do Facebook',
                'verbose_name_plural': 'Páginas do Facebook',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='BusinessManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bm_id', models.CharField(max_length=100, verbose_name='ID do Business Manager')),
                ('nome_bm', models.CharField(max_length=200, verbose_name='Nome do Business Manager')),
                ('data_geracao', models.DateField(blank=True, null=True, verbose_name='Data de geração')),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('restrito', 'Restrito'), ('banido', 'Banido')], default='ativo', max_length=20, verbose_name='Status')),
                ('perfil', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='business_manager', to='profiles.profile', verbose_name='Perfil')),
            ],
            options={
                'verbose_name': 'Business Manager',
                'verbose_name_plural': 'Business Managers',
            },
        ),
        migrations.CreateModel(
            name='WhatsAppLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_telefone', models.CharField(max_length=30, verbose_name='Número de telefone vinculado')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('vinculado', 'Vinculado'), ('falhou', 'Falhou')], default='pendente', max_length=20, verbose_name='Status do vínculo')),
                ('data_vinculo', models.DateField(blank=True, null=True, verbose_name='Data do vínculo')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_links', to='profiles.profile', verbose_name='Perfil')),
            ],
            options={
                'verbose_name': 'Vínculo do WhatsApp',
                'verbose_name_plural': 'Vínculos do WhatsApp',
                'ordering': ['-id'],
            },
        ),
    ]
