# Generated by Django 6.0.7 on 2026-07-31 22:16

import django.db.models.deletion
import profiles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_seed_linear_routes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='fase_atual',
            field=models.ForeignKey(default=profiles.models.fase_inicial_default, on_delete=django.db.models.deletion.PROTECT, related_name='perfis', to='profiles.pipelinestage', verbose_name='Fase atual'),
        ),
    ]
